# Generated by Django 2.1.7 on 2019-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contenttitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('backimage', models.ImageField(default='default.jpg', upload_to='back_pics/')),
            ],
        ),
    ]
