# Generated by Django 2.1.7 on 2019-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190610_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ContentTitle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('backimage', models.ImageField(upload_to='back_pics/')),
            ],
        ),
    ]
