# Generated by Django 2.1.7 on 2019-06-11 07:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190610_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top3post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
