# Generated by Django 2.1.7 on 2019-06-11 08:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190611_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top3post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
